services:

  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "8222:8222"
      - "4222:4222"

  client-gateway:
    build: ./client-gateway
    container_name: client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  products-service:
    build: ./products
    container_name: products-service
    volumes:
      - ./products/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-service:
    build: ./orders
    container_name: orders-service
    depends_on:
      - orders-db
    volumes:
      - ./orders/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVICES=nats://nats-server:4222
      - DATABASE_URL=postgresql://order_user:order_password@orders-db:5432/orders?schema=public

  payments-service:
    build: ./payments
    container_name: payments-service
    ports:
      - ${PAYMENT_PORT}:3003
    volumes:
      - ./payments/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PAYMENT_PORT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}

  orders-db:
    image: postgres:16.2
    container_name: orders-db
    environment:
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_password
      - POSTGRES_DB=orders
    ports:
      - "5432:5432"
    volumes:
      - ./orders/orders-db-data:/var/lib/postgresql/data
